import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import { useForm } from 'react-hook-form';

export default function Home() {
  const { register, handleSubmit } = useForm();
  const onSubmit = async (data) => {
    // const formData = new FormData();
    // formData.append('file', data.file[0]);
    const res = await fetch('api/hello', {
      method: 'GET',
      // body: formData,
    })
      // .then((response) => response.json())
      // .then((data) => alert(data));
      alert(res);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          UNIPA補助ツール
        </h1>
        {/* <form onSubmit={handleSubmit(onSubmit)}> */}
          {/* <input type="file" {...register("file")} name="upload" accept='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' required/> */}
        <form action="api/upload-api" method='post' encType='multipart/form-data'>
          <input type="file" name="upload" accept='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' required/>
          <input type="submit" value="送信する" />
        </form>

        <a href="api/upload-api">Download</a>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
